export const PUZZLES = [
  {
    id: 'p1',
    title: 'Mate in 1 - The Dragon Strikes!',
    description: 'The White Queen can end the battle in one move. Can you find it?',
    fen: 'r1bqkb1r/pppp1ppp/2n2n2/4p3/2B1P3/5N2/PPPP1PPP/RNBQK2R w KQkq - 4 4',
    solution: ['f3g5'],
    hints: ['Look for a move that attacks the King directly!', 'Your Knight on f3 can leap into action!'],
    difficulty: 'squire' as const,
    reward: 50,
  },
  {
    id: 'p2',
    title: 'Fork Attack - Two for One!',
    description: 'Knights are tricky! Find a move that attacks two of the enemy\'s pieces at once.',
    fen: 'r1bqkbnr/pppp1ppp/2n5/4p3/4P3/5N2/PPPP1PPP/RNBQKB1R w KQkq - 2 3',
    solution: ['f3e5'],
    hints: ['A Knight can attack multiple squares at once — a "fork"!', 'The Knight on f3 can jump to e5 and threaten the King AND a Rook!'],
    difficulty: 'squire' as const,
    reward: 50,
  },
  {
    id: 'p3',
    title: 'Pin the Dragon!',
    description: 'A pin is when a piece can\'t move without exposing a more valuable piece. Pin the enemy Knight!',
    fen: 'rnbqk2r/pppp1ppp/4pn2/8/1bPP4/2N5/PP2PPPP/R1BQKBNR w KQkq - 2 4',
    solution: ['c1g5'],
    hints: ['Your Bishop can pin an enemy piece to their King!', 'Move the Bishop on c1 to attack the Knight on f6, which is in line with the enemy King!'],
    difficulty: 'knight' as const,
    reward: 75,
  },
  {
    id: 'p4',
    title: 'Back Rank Checkmate!',
    description: 'The enemy King is trapped on its back rank. Deliver the final blow!',
    fen: '6k1/5ppp/8/8/8/8/8/4R2K w - - 0 1',
    solution: ['e1e8'],
    hints: ['The enemy King cannot escape!', 'Your Rook can march to the back rank for checkmate!'],
    difficulty: 'knight' as const,
    reward: 75,
  },
  {
    id: 'p5',
    title: 'The Windmill!',
    description: 'A famous tactical pattern — find the move that wins decisive material!',
    fen: 'r2q1rk1/ppp2ppp/2n5/3pp3/1b6/2NP1N2/PPP1BPPP/R1BQ1RK1 w - - 0 8',
    solution: ['f3e5'],
    hints: ['Knight forks are powerful. What two pieces can you attack at once?'],
    difficulty: 'bishop' as const,
    reward: 100,
  },
];

export const TUTORIALS = [
  {
    step: 'pawn' as const,
    title: 'The Brave Foot Soldier - Pawn',
    description: 'Pawns are the foot soldiers of your army! They march forward one square at a time, but on their first move they can charge two squares ahead. They capture diagonally!',
    fen: '8/8/8/8/8/8/4P3/8 w - - 0 1',
    highlightSquares: ['e3', 'e4'],
    icon: '♟',
    coachMessage: 'Hello, young knight! I am Merlin, your Chess Wizard. Let\'s learn how the brave Pawn fights! Click the pawn and see where it can go.',
  },
  {
    step: 'rook' as const,
    title: 'The Tower Guardian - Rook',
    description: 'The Rook is a powerful castle tower! It can move any number of squares in a straight line — up, down, left, or right. It\'s great for controlling entire rows and columns!',
    fen: '8/8/8/8/4R3/8/8/8 w - - 0 1',
    highlightSquares: ['e1', 'e2', 'e3', 'e5', 'e6', 'e7', 'e8', 'a4', 'b4', 'c4', 'd4', 'f4', 'g4', 'h4'],
    icon: '♜',
    coachMessage: 'Now meet the mighty Rook! It can zoom across the entire board in a straight line. Click it to see its power!',
  },
  {
    step: 'knight' as const,
    title: 'The Leaping Knight',
    description: 'Knights are the only pieces that can jump over others! They move in an "L" shape — two squares in one direction, then one square to the side. Very tricky!',
    fen: '8/8/8/8/4N3/8/8/8 w - - 0 1',
    highlightSquares: ['d2', 'f2', 'c3', 'g3', 'c5', 'g5', 'd6', 'f6'],
    icon: '♞',
    coachMessage: 'The Knight is the trickiest piece — it jumps in an L-shape and can leap over other pieces! Click it to see the "L" pattern.',
  },
  {
    step: 'bishop' as const,
    title: 'The Diagonal Bishop',
    description: 'The Bishop glides diagonally across the board. Each Bishop stays on its starting color for the entire game, making it a master of one color of squares!',
    fen: '8/8/8/8/4B3/8/8/8 w - - 0 1',
    highlightSquares: ['a8', 'b7', 'c6', 'd5', 'f3', 'g2', 'h1', 'b1', 'c2', 'd3', 'f5', 'g6', 'h7'],
    icon: '♝',
    coachMessage: 'The Bishop rules the diagonals! It always stays on the same color. Let\'s see its sweeping diagonal power!',
  },
  {
    step: 'queen' as const,
    title: 'The All-Powerful Queen',
    description: 'The Queen is the most powerful piece on the board! She can move any number of squares in any direction — like a Rook AND Bishop combined!',
    fen: '8/8/8/8/4Q3/8/8/8 w - - 0 1',
    highlightSquares: ['e1','e2','e3','e5','e6','e7','e8','a4','b4','c4','d4','f4','g4','h4','a8','b7','c6','d5','f3','g2','h1','b1','c2','d3','f5','g6','h7'],
    icon: '♛',
    coachMessage: 'Behold the mighty Queen! She is the most powerful piece — protect her well! But also use her bold power to attack!',
  },
  {
    step: 'king' as const,
    title: 'Protect the King!',
    description: 'The King can move one square in any direction. He is the most important piece — if your King is cornered and cannot escape (Checkmate), the game is over! Protect him!',
    fen: '8/8/8/8/4K3/8/8/8 w - - 0 1',
    highlightSquares: ['d3','e3','f3','d4','f4','d5','e5','f5'],
    icon: '♚',
    coachMessage: 'The King is your most precious piece. One square in any direction. Keep him safe — if he falls, the game is lost!',
  },
  {
    step: 'castling' as const,
    title: 'The Great Castle - Castling!',
    description: 'Castling is a special move where your King and Rook swap positions to keep the King safe. Move the King two squares toward a Rook and the Rook jumps to the other side!',
    fen: 'r3k2r/8/8/8/8/8/8/R3K2R w KQkq - 0 1',
    highlightSquares: ['g1', 'c1'],
    icon: '🏰',
    coachMessage: 'Castling is a special secret move — the King and Rook team up to switch! This is how Knights keep their King safe in the castle. Try it!',
  },
];
